"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, type CSSProperties } from "react";
import { ArrowLeft, ArrowRight, Check, Mail, Phone } from "lucide-react";
import type { ContactRecord, ProductRecord, SectionImageRecord } from "../../lib/content-store";
import { InquiryForm } from "./inquiry-form";
import { ProductLinkCard } from "./product-link-card";

export function HomePageClient({ banners, aboutImage, factoryImages, featured, products, inquiryEmail, contacts }: { banners: SectionImageRecord[]; aboutImage?: SectionImageRecord; factoryImages: SectionImageRecord[]; featured: ProductRecord[]; products: ProductRecord[]; inquiryEmail: string; contacts: ContactRecord[] }) {
  const [slide, setSlide] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setSlide((current) => (current + 1) % Math.max(banners.length, 1)), 5200); return () => window.clearInterval(timer); }, [banners.length]);
  useEffect(() => { if (!window.location.hash) return; const targetId = decodeURIComponent(window.location.hash.slice(1)); const timeout = window.setTimeout(() => document.getElementById(targetId)?.scrollIntoView({ block: "start" }), 120); return () => window.clearTimeout(timeout); }, []);
  const move = (amount: number) => { if (banners.length > 1) setSlide((current) => (current + amount + banners.length) % banners.length); };
  const activeBanner = banners[slide] || banners[0];
  return <main className="renewal-main">
    <section className="renewal-hero" aria-label="Featured renewable energy solutions"><div className="renewal-banner-stage" style={{ "--renewal-banner-image": `url(${activeBanner?.imagePath || ""})` } as CSSProperties}>{banners.map((banner, index) => <Image className={index === slide ? "is-active" : ""} src={banner.imagePath} alt={banner.altText || banner.label} fill priority={index === 0} sizes="100vw" key={banner.id} />)}</div>{banners.length > 1 ? <div className="renewal-hero-controls"><button type="button" onClick={() => move(-1)} aria-label="Previous banner"><ArrowLeft /></button><div>{banners.map((banner, index) => <button className={index === slide ? "is-active" : ""} type="button" onClick={() => setSlide(index)} aria-label={`Show banner ${index + 1}`} key={banner.id} />)}</div><button type="button" onClick={() => move(1)} aria-label="Next banner"><ArrowRight /></button></div> : null}</section>
    <section className="renewal-about" id="about">{aboutImage ? <Image src={aboutImage.imagePath} alt={aboutImage.altText || aboutImage.label} fill sizes="100vw" /> : null}<div className="renewal-shell renewal-about-inner"><div className="renewal-about-copy"><span>ABOUT US</span><h1>Reliable renewable energy sourcing, made simpler.</h1><p>Jiaxing Easyon Technology Co., Ltd. is a China-based export and sourcing company specializing in integrated renewable energy solutions.</p><p>Through our trusted manufacturing network, we provide solar inverters, lithium batteries, energy storage systems and related accessories to customers worldwide.</p><div className="renewal-checks"><span><Check /> One-stop sourcing</span><span><Check /> OEM & ODM available</span><span><Check /> 2-year inverter warranty</span><span><Check /> Professional after-sales support</span></div><Link className="renewal-text-link" href="/about">Learn more about us <ArrowRight size={18} /></Link></div></div></section>
    <section className="renewal-factory" id="factory"><div className="renewal-shell renewal-section-head"><span>OUR WORKSHOP</span><h2>Production visibility from factory floor to export packing.</h2><p>Experienced manufacturing partners, clear quality checks and coordinated international trade support.</p></div><div className="renewal-marquee" aria-label="Factory and office photo gallery"><div className="renewal-marquee-track">{[...factoryImages, ...factoryImages].map((image, index) => <figure key={`${image.id}-${index}`}><Image src={image.imagePath} alt={index < factoryImages.length ? image.altText || image.label : ""} fill sizes="(max-width: 700px) 85vw, 42vw" /></figure>)}</div></div></section>
    <section className="renewal-featured" id="products"><div className="renewal-shell"><div className="renewal-section-head renewal-head-row"><div><span>POPULAR PRODUCTS</span><h2>Three focused product families.</h2></div><Link className="renewal-text-link" href="/products">View all products <ArrowRight size={18} /></Link></div><div className="renewal-product-grid">{featured.map((product) => <ProductLinkCard product={product} key={product.slug} />)}</div></div></section>
    <section className="renewal-contact" id="contact"><div className="renewal-shell renewal-contact-grid"><div className="renewal-contact-copy"><span>CONTACT US</span><h2>Let&apos;s build your next energy project.</h2><p>Share the product, destination and key technical requirements. We will coordinate model selection, quotation and available documentation.</p><div className="renewal-contact-list">{contacts.map((contact) => <section className="renewal-office-block" key={contact.id}><h3>{contact.label}</h3>{contact.email ? <a href={`mailto:${contact.email}`}><Mail /><div><span>Email</span><strong>{contact.email}</strong></div></a> : null}{contact.phone ? <a href={`tel:${contact.phone.replace(/\s/g, "")}`}><Phone /><div><span>Tel</span><strong>{contact.phone}</strong></div></a> : null}</section>)}</div></div><InquiryForm products={products} inquiryEmail={inquiryEmail} /></div></section>
  </main>;
}
